### ISSUE TITLE
内存溢出OutOfMemoryError

### ISSUE THREAD

**Issue by LiuDongCai** [xiaohaibin/XBanner#108]
java.lang.OutOfMemoryError: Failed to allocate a 17 byte allocation with 3920 free bytes and 3KB until OOM
    at android.view.View.<init>(View.java:3853)
    at android.view.View.<init>(View.java:3962)
    at android.widget.ImageView.<init>(ImageView.java:145)
    at android.widget.ImageView.<init>(ImageView.java:140)
    at android.support.v7.widget.AppCompatImageView.<init>(SourceFile:71)
    at android.support.v7.widget.AppCompatImageView.<init>(SourceFile:67)
    at android.support.v7.app.AppCompatViewInflater.b(SourceFile:181)
    at android.support.v7.app.AppCompatViewInflater.a(SourceFile:105)
    at android.support.v7.app.AppCompatDelegateImplV9.createView(SourceFile:1035)
    at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(SourceFile:1092)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.view.View.inflate(View.java:20196)
    at com.stx.xhb.xbanner.XBanner.setData(SourceFile:502)
    at com.stx.xhb.xbanner.XBanner.setData(SourceFile:525)

**Comment by xiaohaibin** [comment]
图片是不是太大了，XBanner不至于导致OOM
