### ISSUE TITLE
implementation 'com.github.xiaohaibin:XBanner:1.7.0' 有个错误

### ISSUE THREAD

**Issue by LiuDongCai** [xiaohaibin/XBanner#156]
java.lang.IllegalArgumentException: pointerIndex out of range
    at android.view.MotionEvent.nativeGetAxisValue(Native Method)
    at android.view.MotionEvent.getX(MotionEvent.java:2179)
    at androidx.viewpager.widget.ViewPager.onTouchEvent(SourceFile:2241)
    at com.stx.xhb.xbanner.XBannerViewPager.onTouchEvent(SourceFile:131)
    at android.view.View.dispatchTouchEvent(View.java:9148)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2680)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2351)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at com.stx.xhb.xbanner.XBanner.dispatchTouchEvent(SourceFile:936)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.widget.ScrollView.dispatchTouchEvent(ScrollView.java:619)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SourceFile:1018)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2747)
    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1840)
    at android.app.Activity.dispatchTouchEvent(Activity.java:3027)
    at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:69)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2708)
    at android.view.View.dispatchPointerEvent(View.java:9358)
    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5044)
    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4874)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4482)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4539)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4390)
    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4356)
    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4364)
    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4337)
    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6940)
    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6813)
    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6784)
    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7030)
    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
    at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
    at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
    at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7001)
    at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7053)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:826)
    at android.view.Choreographer.doCallbacks(Choreographer.java:605)
    at android.view.Choreographer.doFrame(Choreographer.java:573)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:812)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6949)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by xiaohaibin** [comment]
使用最新的1.7.3版本试试，看报错信息有引入AndroidX

**Comment by LiuDongCai** [comment]
是的，我們項目是用AndroidX

**Comment by xiaohaibin** [comment]
有Androidx版本的，可以切换到Androidx版本




| |
萧海斌
邮箱：xhb_199409@163.com
|

签名由 网易邮箱大师 定制

在2020年03月06日 09:35，LiuDongCai 写道：

是的，我們項目是用AndroidX
