### ISSUE TITLE
demo crash

### ISSUE THREAD

**Issue by hardlove** [xiaohaibin/XBanner#213]
version：1.8.9

Process: com.stx.xhb.xbanner, PID: 23282
    java.lang.ArithmeticException: divide by zero
        at com.stx.xhb.xbanner.XBanner.getRealPosition(XBanner.java:791)
        at com.stx.xhb.xbanner.XBanner.access$500(XBanner.java:58)
        at com.stx.xhb.xbanner.XBanner$XBannerPageAdapter.instantiateItem(XBanner.java:1208)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:25156)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25156)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:1002)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:401)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1580)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:849)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:728)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7109)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1103)
        at android.view.View.measure(View.java:25156)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3669)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2294)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2691)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8884)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
        at android.view.Choreographer.doFrame(Choreographer.java:911)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)

**Comment by xiaohaibin** [comment]
version 1.9.0 fix this bug
