### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by LiuDongCai** [xiaohaibin/XBanner#54]
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.stx.xhb.xbanner.XBannerViewPager.getLeft()' on a null object reference
	at com.stx.xhb.xbanner.XBanner.dispatchTouchEvent(SourceFile:742)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.a(SourceFile:1004)
	at com.scwang.smartrefresh.layout.SmartRefreshLayout.dispatchTouchEvent(SourceFile:889)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2519)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2110)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2529)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1802)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2823)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(SourceFile:68)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2486)
	at android.view.View.dispatchPointerEvent(View.java:8865)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4721)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4579)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4078)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4131)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4097)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4234)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4105)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4291)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4078)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4131)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4097)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4105

**Comment by xiaohaibin** [comment]
必现么？版本多少

**Comment by LiuDongCai** [comment]
implementation 'com.xhb:xbanner:1.4.8'

SmartRefreshLayout 内嵌了 这个xbanner 

implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1'

**Comment by xiaohaibin** [comment]
使用这个刷新框架刷新之后出现的么，方便贴下布局代码么，我复现下，谢谢

**Comment by LiuDongCai** [comment]
//设置图片加载器
        banner.loadImage(new XBanner.XBannerAdapter() {
            @Override
            public void loadBanner(XBanner banner, Object model, View view, int position) {
                Glide.with(mContext)
                        .load((String) model)
                        .placeholder(R.drawable.no_photo_80x60)
                        .into((ImageView) view);
            }
        });
        //设置banner动画效果
        banner.setPageTransformer(Transformer.Default);
        //设置禁止自动轮播，默认为true
        banner.setAutoPlayAble(true);
        //图片轮播时间间隔
        banner.setAutoPalyTime(2500);


//設置refreshLayout
        refreshLayout.setEnablePureScrollMode(false);
        refreshLayout.setEnableOverScrollBounce(false);
        refreshLayout.setEnableOverScrollDrag(false);
        refreshLayout.setEnableScrollContentWhenRefreshed(false);
        refreshLayout.setEnableLoadmoreWhenContentNotFull(false);

**Comment by LiuDongCai** [comment]
implementation 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.4-4'
implementation 'com.xhb:xbanner:1.4.8'

**Comment by LiuDongCai** [comment]
目前还不知道怎么出现的，是我丢去云测平台测试，出现的

**Comment by xiaohaibin** [comment]
好的，我看下

**Comment by xiaohaibin** [comment]
我这里测试了下，没问题，暂时加了一个非空判断，请更新1.5.0试试看

**Comment by LiuDongCai** [comment]
好的，我试试

**Comment by LiuDongCai** [comment]
Failed to resolve: com.xhb:xbanner:1.5.0
是1.5.0吗？

**Comment by LiuDongCai** [comment]
1.5.0的无法更新哦？

**Comment by LiuDongCai** [comment]
@xiaohaibin 
Failed to resolve: com.xhb:xbanner:1.5.0
1.5.0的无法更新哦？

**Comment by xiaohaibin** [comment]
稍等，还没更新上去

**Comment by LiuDongCai** [comment]
好，我下午更新看看，下午应该ok了吧

**Comment by xiaohaibin** [comment]
嗯，到时候你注意看下readme上的版本，目前maven库一直推不上去

**Comment by LiuDongCai** [comment]
现在还是1.4.8

**Comment by LiuDongCai** [comment]
一直是1.4.8诶
然后Failed to resolve: com.xhb:xbanner:1.5.0
更新是不是出什么问题了

**Comment by LiuDongCai** [comment]
明天要发版本，有点慌

**Comment by xiaohaibin** [comment]
还没更新成功，今天不知道为啥一直更新不上去

**Comment by LiuDongCai** [comment]
是不是哪里设置错了，我看1.4.9也没有

**Comment by xiaohaibin** [comment]
没有，一直连接超时

**Comment by LiuDongCai** [comment]
这就尴尬了==!
那可咋办

**Comment by xiaohaibin** [comment]
晚上我回家再试下了，可能是公司网络问题，着急的话，你可以暂时把源码下载下来，替换一下

**Comment by LiuDongCai** [comment]
我明天发版本，晚上再试一下吧

**Comment by LiuDongCai** [comment]
网上好像有一些 中央仓库connect time out 的解决方案，你可以看一下是不是同个问题

**Comment by xiaohaibin** [comment]
今天https://bintray.com 挂了，有点尴尬

**Comment by LiuDongCai** [comment]
呃，尴尬，那晚上或者明天试试

**Comment by LiuDongCai** [comment]
我这里打开这个网址是正常的

**Comment by xiaohaibin** [comment]
那就是我司网友问题，晚上回家弄了

**Comment by LiuDongCai** [comment]
好的，麻烦了

**Comment by LiuDongCai** [comment]
还是1.4.8吗==!

**Comment by xiaohaibin** [comment]
bintray 更新有毒呀，一直更新不上去，我家里的也不行==！

**Comment by LiuDongCai** [comment]
呃……这个就gg

**Comment by xiaohaibin** [comment]
可以了，开完会回来终于好了。1.4.9
