### ISSUE TITLE
出现了这个错

### ISSUE THREAD

**Issue by LiuDongCai** [xiaohaibin/XBanner#94]
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.get(ArrayList.java:437)
    at com.stx.xhb.xbanner.XBanner$XBannerPageAdapter$1.onNoDoubleClick(SourceFile:746)
    at com.stx.xhb.xbanner.OnDoubleClickListener.onClick(SourceFile:30)
    at android.view.View.performClick(View.java:7352)
    at android.view.View.performClickInternal(View.java:7318)
    at android.view.View.access$3200(View.java:846)
    at android.view.View$PerformClick.run(View.java:27801)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7032)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by xiaohaibin** [comment]
版本多少，啥情况下出现的呢，集合有做非空判断，理论上不会出现这个问题

**Comment by LiuDongCai** [comment]
implementation 'com.xhb:xbanner:1.5.1'

**Comment by xiaohaibin** [comment]
现在版本都已经到1.6.6了，你更新试下

**Comment by LiuDongCai** [comment]
Failed to resolve: com.xhb:xbanner:1.6.6
Show in File
Show in Project Structure dialog

**Comment by xiaohaibin** [comment]
依赖方式换了，更新一下，包名不变
![image](https://user-images.githubusercontent.com/11681218/57593480-28085d80-756e-11e9-8cd0-4c39fe22c31f.png)
